version: '3.2'

services:
  webapp:
    build:
      context: ./web_app
      dockerfile: Dockerfile  
    ports:
      - "${WEB_PORT}:8050"
    volumes:
      - ./web_app:/code
    environment:
      - DEFAULT_LONGITUDE
      - DEFAULT_LATITUDE
      - WEB_DEBUG
    depends_on:
      - dbapp
    command: ["python3", "-u", "main.py"]

  dbapp:
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "${DATABASE_PORT}:8000"
    depends_on:
      - db
    environment:
      - DATABASE_DEBUG
      - DATABASE_SECRET_KEY
    command: ["python3.8", "manage.py", "runserver", "0.0.0.0:8000", "--insecure"]

  db:
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
